import { Component } from '@angular/core';import { CommonModule } from '@angular/common';import { FormsModule } from '@angular/forms';import { RouterModule } from '@angular/router';
@Component({selector:'app-loan-wizard',standalone:true,imports:[CommonModule,FormsModule,RouterModule],
  template:`<div class="page-container"><div style="display:flex;align-items:center;gap:16px;margin-bottom:24px"><a routerLink="/loans" class="btn btn-secondary btn-sm"><i class="fas fa-arrow-left"></i></a><div><h1 class="page-title">Tạo hồ sơ vay mới</h1><p class="page-subtitle" style="margin:0">Wizard 5 bước · Module DV001</p></div></div>
    <div style="display:flex;gap:4px;margin-bottom:28px">@for(s of steps;track s.num;let i=$index){<div style="flex:1;text-align:center"><div style="height:4px;border-radius:2px;margin-bottom:8px" [style.background]="i<step?'var(--brand-accent)':i===step?'var(--brand-accent)':'var(--border-light)'" [style.opacity]="i<=step?1:0.4"></div><small [style.color]="i<=step?'var(--brand-accent)':'var(--text-tertiary)'" [style.font-weight]="i===step?'700':'400'">{{s.label}}</small></div>}</div>
    <div class="card">
      @if(step===0){<h3 style="margin-bottom:16px"><i class="fas fa-box" style="color:var(--brand-accent);margin-right:8px"></i>Chọn sản phẩm</h3>
        <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:12px">@for(p of products;track p.code){<div style="padding:20px;border:2px solid;border-radius:12px;cursor:pointer" [style.border-color]="form.productType===p.code?'var(--brand-accent)':'var(--border-light)'" [style.background]="form.productType===p.code?'#EFF6FF':'transparent'" (click)="form.productType=p.code"><div style="font-size:1.5rem;margin-bottom:8px">{{p.icon}}</div><strong>{{p.name}}</strong><br><small style="color:var(--text-tertiary)">Lãi suất: {{p.rate}} · Hạn mức: {{p.limit}}</small></div>}</div>}
      @if(step===1){<h3 style="margin-bottom:16px"><i class="fas fa-user" style="color:var(--brand-accent);margin-right:8px"></i>Thông tin khách hàng & tài chính</h3>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Mã khách hàng</label><input [(ngModel)]="form.customerId" placeholder="KH-XXXX" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Thu nhập (VNĐ/tháng)</label><input [(ngModel)]="form.income" type="number" placeholder="15000000" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Chi phí hàng tháng</label><input [(ngModel)]="form.expense" type="number" placeholder="8000000" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Nợ hiện tại</label><input [(ngModel)]="form.existingDebt" type="number" placeholder="0" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div></div>
        @if(form.income&&form.expense){<div class="alert-box alert-info" style="margin-top:16px"><i class="fas fa-calculator" style="color:var(--brand-info)"></i><div><strong>DTI ước tính: {{getDTI()}}%</strong> · {{getDTI()>40?'⚠️ Vượt ngưỡng 40%':'✓ Trong ngưỡng an toàn'}}</div></div>}}
      @if(step===2){<h3 style="margin-bottom:16px"><i class="fas fa-money-bill" style="color:var(--brand-accent);margin-right:8px"></i>Chi tiết khoản vay</h3>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px"><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Số tiền vay (VNĐ)</label><input [(ngModel)]="form.amount" type="number" placeholder="500000000" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Kỳ hạn (tháng)</label><input [(ngModel)]="form.term" type="number" placeholder="36" style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">Mục đích vay</label><input [(ngModel)]="form.purpose" placeholder="Mua nhà, kinh doanh..." style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div><div><label style="font-size:.85rem;font-weight:600;margin-bottom:4px;display:block">TSĐB (nếu có)</label><input [(ngModel)]="form.collateral" placeholder="Sổ đỏ, xe ô tô..." style="width:100%;padding:10px;border:1px solid var(--border-light);border-radius:8px"></div></div>}
      @if(step===3){<h3 style="margin-bottom:16px"><i class="fas fa-upload" style="color:var(--brand-accent);margin-right:8px"></i>Tài liệu đính kèm</h3>
        <div style="display:grid;grid-template-columns:repeat(2,1fr);gap:12px">@for(d of docTypes;track d.name){<div style="padding:20px;border:2px dashed var(--border-light);border-radius:12px;text-align:center;cursor:pointer"><i class="fas fa-cloud-upload-alt" style="font-size:1.5rem;color:var(--text-tertiary);margin-bottom:8px;display:block"></i><strong style="font-size:.85rem">{{d.name}}</strong><br><small style="color:var(--text-tertiary)">{{d.desc}}</small></div>}</div>}
      @if(step===4){<h3 style="margin-bottom:16px"><i class="fas fa-check-circle" style="color:var(--brand-success);margin-right:8px"></i>Xác nhận & Nộp hồ sơ</h3>
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;font-size:.9rem"><div style="padding:12px;background:var(--bg-tertiary);border-radius:8px"><small style="color:var(--text-tertiary)">Sản phẩm</small><br><strong>{{getProductName()}}</strong></div><div style="padding:12px;background:var(--bg-tertiary);border-radius:8px"><small style="color:var(--text-tertiary)">Khách hàng</small><br><strong>{{form.customerId||'—'}}</strong></div><div style="padding:12px;background:var(--bg-tertiary);border-radius:8px"><small style="color:var(--text-tertiary)">Số tiền</small><br><strong>{{form.amount?(form.amount/1e6)+'M VNĐ':'—'}}</strong></div><div style="padding:12px;background:var(--bg-tertiary);border-radius:8px"><small style="color:var(--text-tertiary)">Kỳ hạn</small><br><strong>{{form.term?form.term+' tháng':'—'}}</strong></div></div>
        <button class="btn btn-success" style="width:100%;margin-top:20px;padding:14px;font-size:1rem"><i class="fas fa-paper-plane"></i> Nộp hồ sơ & Chạy Pre-screening</button>}
      <div style="display:flex;justify-content:space-between;margin-top:24px">
        <button class="btn btn-secondary" (click)="step=step-1" [disabled]="step===0"><i class="fas fa-arrow-left"></i> Quay lại</button>
        @if(step<4){<button class="btn btn-primary" (click)="step=step+1">Tiếp theo <i class="fas fa-arrow-right"></i></button>}
      </div>
    </div>
  </div>`,styles:['']
})
export class LoanWizardComponent{step=0;
  steps=[{num:0,label:'Sản phẩm'},{num:1,label:'Khách hàng'},{num:2,label:'Khoản vay'},{num:3,label:'Tài liệu'},{num:4,label:'Xác nhận'}];
  products=[{code:'CONSUMER',name:'Vay tiêu dùng',icon:'🛒',rate:'8-12%/năm',limit:'Tối đa 500M'},{code:'MORTGAGE',name:'Vay mua nhà',icon:'🏠',rate:'7-9%/năm',limit:'Tối đa 5B'},{code:'BUSINESS',name:'Vay SXKD',icon:'🏭',rate:'9-14%/năm',limit:'Tối đa 10B'},{code:'CREDIT_CARD',name:'Thẻ tín dụng',icon:'💳',rate:'18-24%/năm',limit:'Tối đa 200M'}];
  docTypes=[{name:'CMND/CCCD',desc:'Mặt trước + sau'},{name:'Sổ hộ khẩu',desc:'Trang chính + KT3'},{name:'Xác nhận thu nhập',desc:'Sao kê lương 3 tháng'},{name:'Hồ sơ TSĐB',desc:'Sổ đỏ, đăng ký xe'}];
  form:any={productType:'',customerId:'',income:null,expense:null,existingDebt:0,amount:null,term:null,purpose:'',collateral:''};
  getDTI(){if(!this.form.income)return 0;return(((this.form.expense||0)+(this.form.existingDebt||0))/this.form.income*100).toFixed(1);}
  getProductName(){return this.products.find(p=>p.code===this.form.productType)?.name||'—';}
}
