import { Component, OnInit, signal } from '@angular/core'; import { CommonModule } from '@angular/common'; import { RouterModule } from '@angular/router'; import { FormsModule } from '@angular/forms'; import { MockDataService } from '../../core/services/mock-data.service'; import { AutoMLJob } from '../../core/models/data.models';
@Component({
  selector: 'app-automl-dashboard', standalone: true, imports: [CommonModule, RouterModule, FormsModule],
  template: `<div class="page-container"><div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:24px"><div><h1 class="page-title">AutoML & Model Training</h1><p class="page-subtitle">Module ML001-ML005 · H2O.ai · IBM AutoAI · Watson Studio · Feature Store · REST API</p></div><button class="btn btn-primary" (click)="showNewJob.set(true)"><i class="fas fa-plus"></i> Khởi động AutoML Job</button></div>
    <div class="kpi-grid"><div class="kpi-card kpi-blue" style="padding:16px"><div class="kpi-label">Total Jobs</div><div class="kpi-value" style="font-size:1.6rem">{{jobs.length}}</div></div><div class="kpi-card kpi-green" style="padding:16px"><div class="kpi-label">Completed</div><div class="kpi-value" style="font-size:1.6rem">{{completedCount}}</div></div><div class="kpi-card kpi-orange" style="padding:16px"><div class="kpi-label">Running</div><div class="kpi-value" style="font-size:1.6rem">{{runningCount}}</div></div><div class="kpi-card kpi-red" style="padding:16px"><div class="kpi-label">Best AUC</div><div class="kpi-value" style="font-size:1.6rem">0.952</div></div></div>
    <div class="tab-group" style="margin-bottom:20px">
      <div class="tab-item" [class.active]="tab==='jobs'" (click)="tab='jobs'">Jobs</div>
      <div class="tab-item" [class.active]="tab==='leaderboard'" (click)="tab='leaderboard'">Leaderboard</div>
      <div class="tab-item" [class.active]="tab==='datasets'" (click)="tab='datasets'">Datasets (ML002)</div>
      <div class="tab-item" [class.active]="tab==='features'" (click)="tab='features'">Feature Store (ML005)</div>
      <div class="tab-item" [class.active]="tab==='retrain'" (click)="tab='retrain'">Retraining (ML004)</div>
    </div>
    @if(tab==='jobs'){<div class="row-flex">@for(j of jobs;track j.id){<div class="card col-6">
      <div class="card-header"><h3><i class="fas fa-flask" style="margin-right:8px"></i>{{j.name}}</h3><span class="badge" [class]="j.status==='COMPLETED'?'badge-success':j.status==='RUNNING'?'badge-info':j.status==='FAILED'?'badge-danger':'badge-warning'">{{j.status}}</span></div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:14px;font-size:.85rem"><div><small style="color:var(--text-tertiary)">Platform</small><br><strong>{{j.platform}}</strong></div><div><small style="color:var(--text-tertiary)">Dataset</small><br><strong style="font-size:.8rem">{{j.datasetName}}</strong></div><div><small style="color:var(--text-tertiary)">Models Generated</small><br><strong>{{j.modelsGenerated}}</strong></div><div><small style="color:var(--text-tertiary)">Best AUC</small><br><strong style="color:var(--brand-success)">{{j.bestModelAUC||'—'}}</strong></div></div>
      @if(j.status==='RUNNING'){<div class="progress-bar" style="margin-bottom:6px"><div class="progress-fill fill-primary" [style.width.%]="j.progress"></div></div><small style="color:var(--text-tertiary)">{{j.progress}}% complete</small>}
      @if(j.status==='COMPLETED'){<button class="btn btn-sm btn-primary" (click)="tab='leaderboard'"><i class="fas fa-trophy"></i> View Leaderboard</button>}
    </div>}</div>}
    @if(tab==='leaderboard'){<div class="card"><div class="card-header"><h3><i class="fas fa-trophy"></i> Model Leaderboard (ML003)</h3><span class="badge badge-tech">AutoAI REST</span></div>
      <table class="data-table"><thead><tr><th>#</th><th>Model</th><th>AUC</th><th>Precision</th><th>Recall</th><th>F1</th><th>KS</th><th>Gini</th><th>Inference</th><th></th></tr></thead><tbody>
        @for(m of leaderboard;track m.rank){<tr [style.background]="m.rank===1?'#ECFDF5':'transparent'"><td><strong>{{m.rank}}</strong></td><td><strong>{{m.name}}</strong></td><td style="font-weight:800" [style.color]="m.auc>=0.94?'var(--brand-success)':'var(--text-primary)'">{{m.auc}}</td><td>{{m.precision}}</td><td>{{m.recall}}</td><td>{{m.f1}}</td><td>{{m.ks}}</td><td>{{(m.auc*2-1).toFixed(3)}}</td><td style="font-size:.82rem">{{m.inference}}ms</td><td><button class="btn btn-sm" [class]="m.rank===1?'btn-primary':'btn-secondary'">{{m.rank===1?'Deploy':'Chọn'}}</button></td></tr>}
      </tbody></table>
    </div>}
    @if(tab==='datasets'){<div class="card">
      <div class="card-header"><h3><i class="fas fa-database"></i> Dataset Explorer (ML002)</h3><button class="btn btn-primary btn-sm"><i class="fas fa-upload"></i> Upload Dataset</button></div>
      <table class="data-table"><thead><tr><th>Dataset</th><th>Version</th><th>Rows</th><th>Features</th><th>Target</th><th>Missing %</th><th>Size</th><th>Created</th><th></th></tr></thead><tbody>
        @for(d of datasets;track d.name){<tr><td><strong>{{d.name}}</strong></td><td><span class="badge badge-info">{{d.version}}</span></td><td>{{d.rows}}</td><td>{{d.features}}</td><td><span class="badge badge-tech">{{d.target}}</span></td><td [style.color]="d.missing>5?'var(--brand-danger)':'var(--brand-success)'">{{d.missing}}%</td><td>{{d.size}}</td><td style="font-size:.82rem">{{d.created}}</td><td><button class="btn btn-sm btn-secondary"><i class="fas fa-chart-bar"></i> Profile</button></td></tr>}
      </tbody></table>
      <div style="margin-top:16px"><h4 style="margin-bottom:10px"><i class="fas fa-chart-area" style="margin-right:6px"></i>Data Distribution Preview</h4>
        <div style="display:grid;grid-template-columns:repeat(4,1fr);gap:12px">@for(f of dataProfile;track f.name){<div style="padding:12px;background:var(--bg-tertiary);border-radius:10px"><strong style="font-size:.82rem">{{f.name}}</strong><br><small style="color:var(--text-tertiary)">Mean: {{f.mean}} · Std: {{f.std}}</small><div class="progress-bar" style="margin-top:6px;height:6px"><div class="progress-fill fill-primary" [style.width.%]="f.fill"></div></div></div>}</div>
      </div>
    </div>}
    @if(tab==='features'){<div class="card">
      <div class="card-header"><h3><i class="fas fa-cubes"></i> Feature Store (ML005)</h3><button class="btn btn-primary btn-sm"><i class="fas fa-plus"></i> Register Feature</button></div>
      <table class="data-table"><thead><tr><th>Feature</th><th>Type</th><th>Source</th><th>Importance</th><th>Drift</th><th>Last Updated</th><th></th></tr></thead><tbody>
        @for(f of featureStore;track f.name){<tr><td><strong>{{f.name}}</strong><br><small style="color:var(--text-tertiary)">{{f.desc}}</small></td><td><span class="badge badge-info">{{f.type}}</span></td><td>{{f.source}}</td><td><div class="progress-bar" style="width:80px;height:6px;display:inline-block;vertical-align:middle"><div class="progress-fill fill-primary" [style.width.%]="f.importance*100"></div></div> <span style="font-weight:700;font-size:.82rem">{{(f.importance*100).toFixed(0)}}%</span></td><td><span class="badge" [class]="f.drift<0.1?'badge-success':f.drift<0.2?'badge-warning':'badge-danger'">{{f.drift<0.1?'Stable':f.drift<0.2?'Watch':'Drift'}}</span></td><td style="font-size:.82rem">{{f.updated}}</td><td><button class="btn btn-sm btn-secondary"><i class="fas fa-chart-line"></i></button></td></tr>}
      </tbody></table>
    </div>}
    @if(tab==='retrain'){<div class="card">
      <div class="card-header"><h3><i class="fas fa-redo"></i> Retraining Pipeline (ML004)</h3><span class="badge badge-tech">Kubeflow gRPC</span></div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-bottom:20px">
        <div style="padding:16px;background:var(--bg-tertiary);border-radius:12px"><h4 style="margin-bottom:10px">Scheduled Retraining</h4>
          @for(s of retrainSchedules;track s.model){<div style="display:flex;justify-content:space-between;align-items:center;padding:10px;border-bottom:1px solid var(--border-light)"><div><strong>{{s.model}}</strong><br><small style="color:var(--text-tertiary)">{{s.schedule}} · Next: {{s.next}}</small></div><span class="badge" [class]="s.active?'badge-success':'badge-info'">{{s.active?'Active':'Paused'}}</span></div>}
        </div>
        <div style="padding:16px;background:var(--bg-tertiary);border-radius:12px"><h4 style="margin-bottom:10px">Trigger Conditions</h4>
          @for(t of retrainTriggers;track t.name){<div style="display:flex;justify-content:space-between;align-items:center;padding:10px;border-bottom:1px solid var(--border-light)"><div><strong>{{t.name}}</strong><br><small style="color:var(--text-tertiary)">{{t.desc}}</small></div><span class="badge" [class]="t.triggered?'badge-danger':'badge-success'">{{t.triggered?'TRIGGERED':'OK'}}</span></div>}
        </div>
      </div>
      <div style="display:flex;gap:8px"><button class="btn btn-primary"><i class="fas fa-play"></i> Trigger Manual Retrain</button><button class="btn btn-secondary"><i class="fas fa-chart-line"></i> Compare Models</button></div>
    </div>}

    @if(showNewJob()){<div class="modal-overlay" (click)="showNewJob.set(false)"><div class="modal-content" style="max-width:700px" (click)="$event.stopPropagation()">
      <div style="display:flex;justify-content:space-between;margin-bottom:20px"><h2><i class="fas fa-flask" style="margin-right:8px;color:var(--brand-accent)"></i>New AutoML Job (ML001)</h2><button class="btn btn-sm btn-secondary" (click)="showNewJob.set(false)"><i class="fas fa-times"></i></button></div>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">
        <div class="form-group"><label>Job Name</label><input type="text" placeholder="Credit Risk Model v4" style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"></div>
        <div class="form-group"><label>Platform</label><select style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"><option>H2O.ai AutoML</option><option>IBM AutoAI</option><option>Watson Studio</option></select></div>
        <div class="form-group"><label>Dataset</label><select style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"><option>credit_risk_2025Q4.csv</option><option>fraud_detection_2026.csv</option><option>behavioral_scoring.parquet</option></select></div>
        <div class="form-group"><label>Target Variable</label><select style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"><option>default_flag</option><option>fraud_flag</option><option>risk_score</option></select></div>
        <div class="form-group"><label>Optimization Metric</label><select style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"><option>AUC-ROC</option><option>F1 Score</option><option>LogLoss</option><option>KS Statistic</option></select></div>
        <div class="form-group"><label>Max Runtime</label><select style="width:100%;padding:8px 12px;border:1px solid var(--border-light);border-radius:8px"><option>30 minutes</option><option>1 hour</option><option>2 hours</option><option>4 hours</option></select></div>
      </div>
      <div style="display:flex;gap:10px;justify-content:flex-end;margin-top:16px"><button class="btn btn-secondary" (click)="showNewJob.set(false)">Hủy</button><button class="btn btn-primary" (click)="showNewJob.set(false)"><i class="fas fa-rocket"></i> Launch Job</button></div>
    </div></div>}
  </div>`, styles: ['']
})
export class AutoMLDashboardComponent implements OnInit {
  jobs: AutoMLJob[] = []; completedCount = 0; runningCount = 0; tab = 'jobs'; showNewJob = signal(false);
  leaderboard = [{ rank: 1, name: 'XGBoost_22', auc: 0.952, precision: 0.93, recall: 0.90, f1: 0.91, ks: 0.86, inference: 12 }, { rank: 2, name: 'LightGBM_18', auc: 0.948, precision: 0.91, recall: 0.89, f1: 0.90, ks: 0.84, inference: 8 }, { rank: 3, name: 'RandomForest_15', auc: 0.935, precision: 0.90, recall: 0.87, f1: 0.88, ks: 0.82, inference: 15 }, { rank: 4, name: 'DeepLearning_03', auc: 0.921, precision: 0.88, recall: 0.85, f1: 0.86, ks: 0.80, inference: 45 }, { rank: 5, name: 'GBM_11', auc: 0.918, precision: 0.87, recall: 0.84, f1: 0.85, ks: 0.78, inference: 10 }];
  datasets = [{ name: 'credit_risk_2025Q4.csv', version: 'v4.1', rows: '125,840', features: 42, target: 'default_flag', missing: 2.3, size: '48MB', created: '15/01/2026' }, { name: 'fraud_detection_2026.csv', version: 'v2.0', rows: '89,200', features: 35, target: 'fraud_flag', missing: 1.1, size: '32MB', created: '01/02/2026' }, { name: 'behavioral_scoring.parquet', version: 'v3.0', rows: '245,000', features: 58, target: 'risk_score', missing: 0.5, size: '120MB', created: '20/12/2025' }];
  dataProfile = [{ name: 'Monthly Income', mean: '15.2M', std: '8.4M', fill: 72 }, { name: 'Outstanding Debt', mean: '180M', std: '250M', fill: 45 }, { name: 'Payment History', mean: '0.85', std: '0.12', fill: 85 }, { name: 'Employment Years', mean: '5.2', std: '3.8', fill: 52 }, { name: 'DTI Ratio', mean: '32%', std: '12%', fill: 64 }, { name: 'Age', mean: '38', std: '11', fill: 58 }, { name: 'Num Accounts', mean: '2.4', std: '1.2', fill: 48 }, { name: 'Credit Utilization', mean: '45%', std: '22%', fill: 45 }];
  featureStore = [{ name: 'payment_history_score', desc: 'Normalized payment behavior', type: 'Numeric', source: 'Transaction DB', importance: 0.32, drift: 0.06, updated: '25/02/2026' }, { name: 'monthly_income', desc: 'Verified monthly income', type: 'Numeric', source: 'Payroll API', importance: 0.21, drift: 0.25, updated: '25/02/2026' }, { name: 'outstanding_balance', desc: 'Total outstanding debt', type: 'Numeric', source: 'Core Banking', importance: 0.15, drift: 0.15, updated: '25/02/2026' }, { name: 'employment_duration', desc: 'Years at current employer', type: 'Numeric', source: 'HR System', importance: 0.11, drift: 0.03, updated: '24/02/2026' }, { name: 'dti_ratio', desc: 'Debt-to-income ratio', type: 'Derived', source: 'Calculated', importance: 0.08, drift: 0.09, updated: '25/02/2026' }, { name: 'customer_segment', desc: 'AI-derived customer cluster', type: 'Categorical', source: 'PredictionIO', importance: 0.05, drift: 0.04, updated: '25/02/2026' }];
  retrainSchedules = [{ model: 'XGBoost Credit Risk', schedule: 'Monthly', next: '01/03/2026', active: true }, { model: 'LightGBM Fraud', schedule: 'Weekly', next: '03/03/2026', active: true }, { model: 'Behavioral Model', schedule: 'Quarterly', next: '01/04/2026', active: false }];
  retrainTriggers = [{ name: 'PSI Threshold', desc: 'Population Stability Index > 0.20', triggered: true }, { name: 'AUC Degradation', desc: 'AUC dropped > 2% from baseline', triggered: false }, { name: 'Data Volume', desc: '> 10,000 new samples since last train', triggered: true }];
  constructor(private m: MockDataService) { } ngOnInit() { this.jobs = this.m.getAutoMLJobs(); this.completedCount = this.jobs.filter(j => j.status === 'COMPLETED').length; this.runningCount = this.jobs.filter(j => j.status === 'RUNNING').length; }
}
